config/routes.rb
Rails.application.routes.draw do


  get 'users/new'
  get 'users/ushow'
  # put 'users/show'
  post 'users/create'
  get 'users/uedit'
  put 'users/uupdate'
  # patch 'users/update'
  delete 'users/udestroy'
  post 'users/suspend'
  post 'users/active'

  match '/users', to: 'users#index', via: 'get'
  match 'user', to: 'users#show', via: 'get'

  devise_for :admins
  resources :minutes
  resources :companies
  # devise_for :users, class_name: 'FormUser', :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  devise_for :users, :controllers => { :omniauth_callbacks => "my_engine/omniauth_callbacks" }, :class_name => "FormUser", module: :devise

  get '/auth/:provider/callback', to: 'sessions#create'
  get 'welcome/index'

  # facebook sign in
  # devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  # google+ sign in
  # devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :custome_bookings
  resources :bookings

  resources :customers
  resources :cleaners

  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Routing for facebook authentication controller
  devise_scope :user do
    get '/users/auth/:provider/upgrade' => 'omniauth_callbacks#upgrade', as: :user_omniauth_upgrade
    get '/users/auth/:provider/setup', :to => 'omniauth_callbacks#setup'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable,
  #        :omniauthable, :omniauth_providers => [:facebook]
  devise :omniauthable, :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable

  has_and_belongs_to_many :companies
	accepts_nested_attributes_for :companies

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def has_companies?
	  errors.add(:companies, "must be specified.") if self.companies.blank?
	end

  def full_name
    ([first_name, last_name] - ['']).compact.join(' ')
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy, :full_name]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def ushow
    @user = User.find_by_id(params[:format])
  end

  def uedit
    @user = User.find_by_id(params[:format])
  end

  def uupdate
    @user = User.find_by_id(params[:format])
    user = params[:user]
    @user.name = user[:name]
    @user.first_name = user[:first_name]
    @user.last_name = user[:last_name]
    @user.email = user[:email]
    if user[:password] != nil
      @user.password = user[:password]
      @user.password_confirmation = user[:password_confirmation]
    end

    @user.companies = user[:company_ids].present? ? Company.where(id: user[:company_ids]) : [ ]

    if @user.save
      redirect_to users_ushow_path(@user), notice: 'User was successfully updated.'
    else
      format.html { render :ushow }
      format.json { render json: @user.errors, status: :unprocessable_entity }
    end

  end

  # DELETE /users/1
  # DELETE /users/1.json
  def udestroy
    @user = User.find_by_id(params[:format])
    if @user.destroy
      redirect_to users_path, notice: 'User was successfully destroyed.'
    else
      render :index
    end
  end

  def suspend
    @user = User.find_by_id(params[:format])
    if @user.update(suspend: true)
      redirect_to users_path, notice: 'User was successfully updated.'
    else
      render :index
    end
  end

  def active
    @user = User.find_by_id(params[:format])

    if @user.update(suspend: false)
      redirect_to users_path, notice: 'User was successfully updated.'
    else
      render :index
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :first_name, :last_name, :email, :password, :password_confirmation, :suspend, companies_ids: [])
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= bootstrap_form_for(user, url: users_create_path(user), method: :put, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-8") do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.text_field :first_name%>
  </div>

  <div class="field">
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.collection_check_boxes :company_ids, Company.all, :id, :name, label: "Companies" do |c| %>
      <div class="field">
      <%= c.check_box %>
      <%= c.label %>
    <% end %>
  </div>

  <div class="actions col-sm-offset-1" align="left">
    <%= f.submit class: "btn btn-primary", value: "CREATE USER >>" %>
  </div>

<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<div class="panel panel-default">
  <div class="panel-body">
    <table class="table table-striped table-condensed table-responsive">
      <thead>
        <tr>
          <th>Name</th>
          <th>Full Name</th>
          <th>Email</th>
          <th>Suspend/Active</th>
          <th>Action</th>
        </tr>
      </thead>

      <tbody>
        <% unless @users.empty? %>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.full_name %></td>
              <td><%= user.email %></td>
              <td>
                <%= link_to 'Suspend', users_suspend_path(user), method: :post, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger btn-xs' %>
                <%= link_to 'Active', users_active_path(user), method: :post, data: { confirm: 'Are you sure?' } , class: "btn btn-info btn-xs"  %>
              </td>
              <td>
                <%= link_to 'Show', users_ushow_path(user), class: 'btn btn-default btn-xs' %>
                <%= link_to 'Edit', users_uedit_path(user), class: "btn btn-info btn-xs"  %>
                <%= link_to 'Destroy', users_udestroy_path(user), method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger btn-xs" %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="panel-footer">
    <%= link_to('New User', users_new_path, class: "btn btn-success btn-sm") %>
  </div>
</div>

app/views/users/new.html.erb
<h1>New Company</h1>

<% user = @user %>
<%= bootstrap_form_for(user, url: users_create_path(user), layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-8") do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.text_field :first_name%>
  </div>

  <div class="field">
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.collection_check_boxes :company_ids, Company.all, :id, :name, label: "Companies" do |c| %>
      <div class="field">
      <%= c.check_box %>
      <%= c.label %>
    <% end %>
  </div>

  <div class="actions col-sm-offset-1" align="left">
    <%= f.submit class: "btn btn-primary", value: "CREATE USER >>" %>
  </div>

<% end %>

<nav aria-label="...">
  <ul class="pager">
    <li class="previous">
      <a href="/users"><span aria-hidden="true">&larr;</span> Back</a>
    </li>
  </ul>
</nav>

app/views/users/uedit.html.erb
<h1>Editing Company</h1>

<% user = @user %>
<%= bootstrap_form_for(user, url: users_uupdate_path(user), method: :put, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-8") do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.text_field :first_name%>
  </div>

  <div class="field">
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.collection_check_boxes :company_ids, Company.all, :id, :name, label: "Companies" do |c| %>
      <div class="field">
      <%= c.check_box %>
      <%= c.label %>
    <% end %>
  </div>

  <div class="actions col-sm-offset-1" align="left">
    <%= f.submit class: "btn btn-primary", value: "UPDATE USER" %>
  </div>

<% end %>

<nav aria-label="...">
  <ul class="pager">
    <li class="previous">
      <%= link_to 'Back', users_path %>
    </li>

    <li class="previous">
      <%= link_to 'Show', users_ushow_path(@user) %>
    </li>
  </ul>
</nav>

app/views/users/ushow.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <p>
      <div class="form-group">
        <label class="col-md-2 control-label">
          Name:
        </label>
        <%= @user.name %>
      </div>

      <div class="form-group">
        <label class="col-md-2 control-label">
          First Name:
        </label>
        <%= @user.first_name %>
      </div>

      <div class="form-group">
        <label class="col-md-2 control-label">
          Last Name:
        </label>
        <%= @user.last_name %>
      </div>

      <div class="form-group">
        <label class="col-md-2 control-label">
          Email:
        </label>
        <%= @user.email %>
      </div>

      <div class="form-group">
        <label class="col-md-2 control-label">
          Suspend:
        </label>
        <%= @user.suspend ? "true" : "false"%>

      </div>

      <div class="form-group">
        <label class="col-md-2 control-label">
          Companies:
          <%= @user.companies.pluck(:name).join(', ') %>
        </label>
      </div>
    </p>
  </div>

  <div class="panel-footer">
    <nav aria-label="...">
      <ul class="pager">
        <li class="previous">
          <%= link_to 'Back', users_path %>
        </li>
        <li class="previous">
          <%= link_to 'Edit', users_uedit_path(@user) %>
        </li>
      </ul>
    </nav>
  </div>
</div>